import React, { useState, useRef } from 'react';
import api from '../services/api';
import { useToast } from '../context/ToastContext';
const CreatePost = ({ refreshPosts }) => {
  const [isExpanded, setIsExpanded] = useState(false);
  const [formData, setFormData] = useState({ title: '', tags: '', content: '' });
  const [imagePreview, setImagePreview] = useState(null);
  const [videoPreview, setVideoPreview] = useState(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isGeneratingTitle, setIsGeneratingTitle] = useState(false);
  const [isGeneratingTags, setIsGeneratingTags] = useState(false);
  const { showToast } = useToast();
  const fileInputRef = useRef(null);
  const videoInputRef = useRef(null);

  const handleExpand = () => setIsExpanded(true);

  const handleCancel = () => {
    setIsExpanded(false);
    setFormData({ title: '', tags: '', content: '' });
    clearImage();
    clearVideo();
  };

  const handleGenerate = async (type) => {
    if (!formData.content.trim()) {
      showToast(`Please enter a description first to generate a ${type}.`, "warning");
      return;
    }
    if (type === 'title') setIsGeneratingTitle(true);
    else setIsGeneratingTags(true);

    try {
      const res = await api.post('/ai/generate-metadata', { content: formData.content, type });
      if (type === 'title') {
          setFormData(prev => ({...prev, title: res.result}));
      } else {
          setFormData(prev => ({...prev, tags: res.result}));
      }
      showToast(`${type === 'title' ? 'Title' : 'Tags'} generated by AI!`, "success");
    } catch (err) {
      showToast(`AI generation failed: ` + err.message, "error");
    } finally {
      if (type === 'title') setIsGeneratingTitle(false);
      else setIsGeneratingTags(false);
    }
  };

  const handleImageChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (ev) => setImagePreview(ev.target.result);
      reader.readAsDataURL(file);
    } else {
      clearImage();
    }
  };

  const clearImage = () => {
    setImagePreview(null);
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  const handleVideoChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      if (file.size > 6 * 1024 * 1024) { 
        showToast("Video size cannot exceed 6MB.", "error");
        clearVideo();
        return;
      }

      const video = document.createElement('video');
      video.preload = 'metadata';
      
      video.onloadedmetadata = () => {
        URL.revokeObjectURL(video.src);
        if (video.duration > 60) {
          showToast("Video duration cannot exceed 60 seconds.", "error");
          clearVideo();
          return;
        }
        
        const reader = new FileReader();
        reader.onload = (ev) => setVideoPreview(ev.target.result);
        reader.readAsDataURL(file);
      };

      video.onerror = () => {
        URL.revokeObjectURL(video.src);
        showToast("Failed to read video file format.", "error");
        clearVideo();
      };

      video.src = URL.createObjectURL(file);
    } else {
      clearVideo();
    }
  };

  const clearVideo = () => {
    setVideoPreview(null);
    if (videoInputRef.current) videoInputRef.current.value = '';
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (isSubmitting) return;
    setIsSubmitting(true);

    const tagsArray = formData.tags.split(',').map(t => t.trim()).filter(t => t.length > 0);
    
    try {
      await api.post('/posts', {
        title: formData.title,
        content: formData.content,
        tags: tagsArray,
        image: imagePreview,
        video: videoPreview
      });
      showToast("Post published successfully!", "success");
      refreshPosts();
      handleCancel();
    } catch (err) {
      showToast("Failed to create post: " + err.message, "error");
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!isExpanded) {
    return (
      <div className="card">
        <input 
          type="text" 
          placeholder="Create a new post..." 
          className="form-group" 
          style={{ margin: 0, width: '100%', padding: '0.8rem', border: '1px solid var(--border-color)', borderRadius: 'var(--radius)', cursor: 'pointer', background: 'var(--bg-light)', color: 'var(--text-dark)' }} 
          readOnly
          onClick={handleExpand}
        />
      </div>
    );
  }

  return (
    <div className="card" id="create-post-card">
      <h3 style={{ marginBottom: '1rem' }}>Create a Post</h3>
      <form onSubmit={handleSubmit} id="create-post-form">
        <div className="form-group" style={{ display: 'flex', gap: '0.5rem', alignItems: 'center' }}>
          <input 
            type="text" 
            placeholder="Title" 
            required 
            style={{ fontWeight: 600, fontSize: '1.1rem', flex: 1 }}
            value={formData.title}
            onChange={e => setFormData({...formData, title: e.target.value})}
          />
          <button 
            type="button" 
            onClick={() => handleGenerate('title')} 
            className="btn btn-sm" 
            title="Auto-generate Title from description"
            style={{ background: 'var(--primary-color)', color: 'white', padding: '0.6rem 0.8rem', borderRadius: 'var(--radius)', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '0.4rem', border: 'none', fontWeight: 'bold' }}
            disabled={isGeneratingTitle}
          >
            <i className={`fa-solid ${isGeneratingTitle ? 'fa-spinner fa-spin' : 'fa-wand-magic-sparkles'}`}></i> {isGeneratingTitle ? 'Generating...' : 'AI Title'}
          </button>
        </div>
        <div className="form-group" style={{ display: 'flex', gap: '0.5rem', alignItems: 'center' }}>
          <input 
            type="text" 
            placeholder="Tags (comma separated) e.g., Javascript, Help" 
            required
            style={{ flex: 1 }}
            value={formData.tags}
            onChange={e => setFormData({...formData, tags: e.target.value})}
          />
          <button 
            type="button" 
            onClick={() => handleGenerate('tags')} 
            className="btn btn-sm"
            title="Auto-generate Tags from description" 
            style={{ background: 'var(--primary-color)', color: 'white', padding: '0.6rem 0.8rem', borderRadius: 'var(--radius)', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '0.4rem', border: 'none', fontWeight: 'bold' }}
            disabled={isGeneratingTags}
          >
            <i className={`fa-solid ${isGeneratingTags ? 'fa-spinner fa-spin' : 'fa-tags'}`}></i> {isGeneratingTags ? 'Generating...' : 'AI Tags'}
          </button>
        </div>
        <div className="form-group">
          <textarea 
            placeholder="Share your knowledge..." 
            rows="5" 
            required
            value={formData.content}
            onChange={e => setFormData({...formData, content: e.target.value})}
          ></textarea>
        </div>
        <div className="form-group" style={{ display: 'flex', gap: '1rem', alignItems: 'flex-end', flexWrap: 'wrap' }}>
          <div>
            <label style={{ fontSize: '0.9rem' }}>Attach an Image (Optional):</label>
            <input 
              type="file" 
              accept="image/*" 
              ref={fileInputRef}
              onChange={handleImageChange}
              style={{ padding: '0.5rem', background: 'var(--bg-light)', border: '1px dashed var(--border-color)', cursor: 'pointer', display: 'block' }} 
            />
          </div>
          {imagePreview && (
            <div style={{ display: 'flex', alignItems: 'flex-start' }}>
              <img src={imagePreview} alt="Preview" style={{ maxHeight: '80px', maxWidth: '150px', objectFit: 'cover', borderRadius: 'var(--radius)', border: '1px solid var(--border-color)' }} />
              <button 
                type="button" 
                onClick={clearImage}
                className="btn btn-sm" 
                style={{ background: 'var(--bg-card)', color: 'var(--danger)', border: '1px solid var(--danger)', borderRadius: '50%', width: '24px', height: '24px', padding: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', marginLeft: '0.5rem', cursor: 'pointer' }}
                title="Clear Image"
              >
                &times;
              </button>
            </div>
          )}

          <div>
            <label style={{ fontSize: '0.9rem' }}>Attach a Video (Max 60s, 6MB):</label>
            <input 
              type="file" 
              accept="video/*" 
              ref={videoInputRef}
              onChange={handleVideoChange}
              style={{ padding: '0.5rem', background: 'var(--bg-light)', border: '1px dashed var(--border-color)', cursor: 'pointer', display: 'block' }} 
            />
          </div>
          {videoPreview && (
            <div style={{ display: 'flex', alignItems: 'flex-start' }}>
              <video src={videoPreview} style={{ maxHeight: '80px', maxWidth: '150px', objectFit: 'cover', borderRadius: 'var(--radius)', border: '1px solid var(--border-color)' }} muted autoPlay loop />
              <button 
                type="button" 
                onClick={clearVideo}
                className="btn btn-sm" 
                style={{ background: 'var(--bg-card)', color: 'var(--danger)', border: '1px solid var(--danger)', borderRadius: '50%', width: '24px', height: '24px', padding: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', marginLeft: '0.5rem', cursor: 'pointer' }}
                title="Clear Video"
              >
                &times;
              </button>
            </div>
          )}
        </div>
        
        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.5rem' }}>
          <button type="button" className="btn btn-secondary" onClick={handleCancel} disabled={isSubmitting}>Cancel</button>
          <button type="submit" className="btn btn-primary" disabled={isSubmitting}>
              {isSubmitting ? 'Publishing...' : 'Publish Post'}
          </button>
        </div>
      </form>
    </div>
  );
};

export default CreatePost;
